version : '3.3'
services: 
  app:
    # image: 'node:14'
    build:
      context: .
      dockerfile: ./persons-frontend/Dockerfile
    container_name: app
    restart: unless-stopped
    env_file: ./persons-frontend/.env
    environment:
      HOSTNAME: api
    ports:
      - "5050:5050"
    volumes:
      - ./persons-frontend/node_modules
    command:
       bash -c 'ng serve --host 0.0.0.0 --port 5050 --disable-host-check'
    links:
      - "api:api"

  api:
    # image: 'node:alpine'
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: api
    restart: unless-stopped
    env_file: ./server/.env
    environment:
      REDIS_HOST: redis
    ports:
      - "3333:3333"
    volumes:
      - ./server/node_modules
    command:
       bash -c 'npm start'
      
  redis:
    image: 'redis'
    container_name: redis
    restart: on-failure
    ports:
        - "6379:6379"